services:

  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./db:/app/db
      - ./models:/app/models     # Mount machine learning model folder
    environment:
      - ENV=docker-compose

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
